### ISSUE TITLE
Any chance on a version that has been modified and confirmed to work with XE

### ISSUE THREAD

**Issue by AkikoOrenji** [lschilde/Sharing_APEX_SERT_21_2#1]
I just commented out the XE check from the installer but having a few problems post install. 

Once i get it working i'd be happy to submit a PR with the changes required but i'm stuck.

**Comment by AkikoOrenji** [comment]
The install appears to be successful but display the following error at the end 



```
Please see the APEX-SERT Installation Guide for detailed post-installation steps.
connect as SV_SERT_LAUNCHER for SERT Launcher Web Service part 2
ERROR:
ORA-12514: TNS:listener does not currently know of service requested in connect 
descriptor 
```

Clicking the javascript link added manually as directed at the end of the installer from a logged on admin in the workspace i get the following error.

![image](https://github.com/lschilde/Sharing_APEX_SERT_21_2/assets/30274508/049aa7c4-13d9-4a2a-8ab0-f85926b6674b)

When i try and access the sert application ID directly it tells me i need to log into the workspace.

![image](https://github.com/lschilde/Sharing_APEX_SERT_21_2/assets/30274508/7e8f9d34-9e1f-410e-9326-711dc3577555)

ORDS is also throwing out the following traces.


```
Caused by: oracle.dbtools.common.ucp.ConnectionLabelingException: Error occurred when attempting to configure url: jdbc:oracle:thin:@//localhost:1521/XEPDB1 with labels: {oracle.dbtools.jdbc.label.cleanup=RECYCLE, oracle.dbtools.jdbc.label.schema=SV_SERT_LAUNCHER}
        at oracle.dbtools.common.ucp.LabelingCallback.handle(LabelingCallback.java:192)
        at oracle.dbtools.common.ucp.LabelingCallback.proxyToSchema(LabelingCallback.java:355)
        at oracle.dbtools.common.ucp.LabelingCallback.configure(LabelingCallback.java:78)
        at oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnectionAndValidateHelper(UniversalConnectionPoolImpl.java:258)
        at oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnectionAndValidate(UniversalConnectionPoolImpl.java:166)
        at oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnection(UniversalConnectionPoolImpl.java:139)
        at oracle.ucp.jdbc.JDBCConnectionPool.borrowConnection(JDBCConnectionPool.java:185)
        at oracle.ucp.jdbc.oracle.OracleJDBCConnectionPool.borrowConnection(OracleJDBCConnectionPool.java:611)
        at oracle.ucp.jdbc.oracle.OracleConnectionConnectionPool.borrowConnection(OracleConnectionConnectionPool.java:119)
        at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1882)
        at oracle.ucp.jdbc.PoolDataSourceImpl$3.build(PoolDataSourceImpl.java:4055)
        at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1825)
        at oracle.dbtools.common.ucp.PoolDataSourceDelegate.getConnection(PoolDataSourceDelegate.java:114)
        at oracle.dbtools.common.config.db.RefreshablePoolDataSource.getConnection(RefreshablePoolDataSource.java:110)
        at oracle.dbtools.common.ucp.PoolDataSourceDelegate.getConnection(PoolDataSourceDelegate.java:114)
        at oracle.dbtools.common.ucp.PoolDataSourceDelegate.getConnection(PoolDataSourceDelegate.java:114)
        at oracle.dbtools.common.ucp.PoolDataSourceDelegate.getConnection(PoolDataSourceDelegate.java:99)
        at oracle.dbtools.common.jdbc.DataSourceConnection.getPooledConnection(DataSourceConnection.java:210)
        ... 86 more
Caused by: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:630)
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:559)
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:554)
        at oracle.jdbc.driver.T4CTTIfun.processError(T4CTTIfun.java:1377)
        at oracle.jdbc.driver.T4CTTIoauthenticate.processError(T4CTTIoauthenticate.java:784)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:772)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:299)
        at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:452)
        at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:2103)
        at oracle.jdbc.driver.T4CConnection.doProxySession(T4CConnection.java:3735)
        at oracle.jdbc.driver.PhysicalConnection.openProxySession(PhysicalConnection.java:3311)
        at oracle.ucp.jdbc.proxy.oracle$1ucp$1jdbc$1proxy$1oracle$1ConnectionProxy$2oracle$1jdbc$1internal$1OracleConnection$$$Proxy.openProxySession(Unknown Source)
        at oracle.dbtools.common.ucp.LabelingCallback$ProxySchemaTask.call(LabelingCallback.java:434)
        at oracle.dbtools.common.ucp.LabelingCallback$ProxySchemaTask.call(LabelingCallback.java:422)
        at oracle.dbtools.common.concurrent.RetryStrategy.execute(RetryStrategy.java:46)
        at oracle.dbtools.common.ucp.LabelingCallback.proxyToSchema(LabelingCallback.java:342)
        ... 102 more
```

Any ideas what might be going wrong here ?

**Comment by AkikoOrenji** [comment]
Should also note that the sert-admin portal works fine and i can log in there were no reported issues with creating the SV_SERT_LAUNCHER user as part of the sert install script. 

```
==================================================================================
= CREATING SV_SERT_LAUNCHER USER
==================================================================================

Listing all available tablespaces...


Tablespace Name                                                                 
------------------------------                                                  
APEX_2300442463290518                                                           
APEX_2400312652450323                                                           
SYSAUX                                                                          
SYSTEM                                                                          
TEMP                                                                            
UNDOTBS1                                                                        
USERS                                                                           

Please enter the default tablespace to be used for SV_SERT_LAUNCHER [USERS] : 
Please enter the temporary tablespace to be used for SV_SERT_LAUNCHER [TEMP] : 

User created.


Grant succeeded.
```

**Comment by lschilde** [comment]
Hi Akiko, 

thanks for reporting this... I think you had a miss config in installation script.  

Error _`ORA-12514: TNS:listener does not currently know of service requested in connect  descriptor`_ 
mean that line 66 did not work - please check ins_auto_setup.sql
```
--
def db_conn_string             = **'localhost:1521/orcl'**      -- DB instance connection 
--
```

you need to update it before running the installation. Point of it is at few points we are doing something like 
_connect SV_SERT_LAUNCHER/^schema_password@^db_conn_string_

to run 
_@@app/_install_ws.sql apex-sert_launcher_part2.sql_

So you need to make sure line number 66 works. You can simply uninstall and install again.

At the end hopefully this will resolve your issue.

**Comment by lschilde** [comment]
Interested to know if we can get it going on XE too since original installation said it might not work. I never tested this part. So appreciate the feedback.

**Comment by AkikoOrenji** [comment]
Thanks for the pointer. This resolved the issue. Root cause was user error and failure to read your [instructions](https://lschilde.blogspot.com/2023/03/lets-talk-apex-security-apex-sert.html) fully 🥲 . I had not updated the DB connection string to take into account using PDB in the ins.sql file hence failing when then script tried to setup the sert web service (API).  To a beginner it looked like installer had completed but as you say it had not fully done so. 

```
PROMPT  http(s)://HOST:PORT/DAD/f?p=SERT_ADMIN
PROMPT
PROMPT  Please see the APEX-SERT Installation Guide for detailed post-installation steps.
PROMPT

-- SERT Launcher Web Service part 2
PROMPT connect as SV_SERT_LAUNCHER for SERT Launcher Web Service part 2
connect SV_SERT_LAUNCHER/^schema_password@**^db_conn_string**
@@app/_install_ws.sql apex-sert_launcher_part2.sql

```
![image](https://github.com/lschilde/Sharing_APEX_SERT_21_2/assets/30274508/03ac99e9-e624-48f4-97fd-dd6541173120)

For those wanting to run apex-sert in a lab or offline to audit a workspace or app exported from a production system you can follow the instructions in this forum post to build yourself an Apex instance with Oracle XE. 

https://forums.oracle.com/ords/apexds/post/how-do-we-configure-ords-for-apex-running-on-pluggable-data-7182#comment_323523248199685952235930533846015697729

In the above its says run the below but REST and PUBLIC are swapped around the wrong way

`Execute **ALTER USER APEX\_PUBLIC\_REST\_USER ACCOUNT UNLOCK;**  `

You actually need to run 

`Execute **ALTER USER APEX\_REST\_PUBLIC_USER ACCOUNT UNLOCK;**  `

Also you now install ords with 

`\ords\bin\>\ords.exe --config ..\ordsconfig install`

and restart it when you close the command shell running ords with 

`\ords\bin>ords.exe --config ..\ordsconfig serve`

**Before you install ORDS** however you should install apex-sert and import your workspace or app export into your apex instance (follow the instructions provided by Oracle [here](https://docs.oracle.com/en/database/oracle/apex/22.1/aeadm/installing-an-application.html#GUID-3C25C477-A356-44C0-ACBE-770A458486F1) to do so) 

Once that's done you can follow the rest of the blog post to install ORDS and it should just start serving your apex installation automatically if the ORDS install script was successful. 

If you already have ORDS running before you install apex-sert uninstalling ORDS and reinstalling it worked for me. 

`\ords\bin\>ords.exe --config ..\ordsconfig uninstall` and then delete the ordsconfig directory and then run the install again.

The lines that can be commented out from the ins.sql to install on Oracle XE are as follows:

```

--  =================
--  =================  Check for XE edition 
--  =================
/*PROMPT  ...... Test for XE Edition of Oracle
declare
    l_edition varchar2(30) := 'notXE';
--begin
--        begin
 --           execute immediate
--              'select edition from registry$ WHERE cid=''CATPROC'''
--            into l_edition;
--        exception when others then
--            null;
--        end;


--    if l_edition = 'XE' then
--        dbms_output.put_line('APEX-SERT will not run on the XE edition of Oracle.');
--        execute immediate 'bogus statement to force exit';
--    end if;
--end;
--/*/
```

**Comment by lschilde** [comment]
Excellent thanks for letting me know. :D
